name: CI

on:
  release:
    types: [created]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 9.5.0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm install

#      - name: Run Tests
#        run: pnpm test

      - run: pnpm build

  publish-npm:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 9.5.0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org/'

      - run: pnpm install

      - name: Configure Git for CI
        run: |
          git config --global user.email "ci@githubuser.com"
          git config --global user.name "Coingecko API CI"

      - name: Generate Docs
        run: pnpm doc-gen

      - name: Bump version and tag release
        run: pnpm release

      - name: Push tags and updated changelog
        run: git push --follow-tags origin main

      - name: Build and Publish to NPM
        run: |
          pnpm build
          pnpm publish --access public

      - uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: docs
